# PyTorch分类器配置
model:
  instantiation:
    model_path: "/home/he/art_ryf/model/net/cifar10.py"
    weight_path: "/home/he/art_ryf/model/weight/cifar_50.pth"
    model_name: "Tudui"
    parameters:
  estimator:
    framework: "pytorch"
    task: "classification"
    parameters:
      input_shape: [3, 32, 32]
      nb_classes: 10
      clip_values: [0,1]
      device: "cuda"
      device_type: "gpu"
evaluation:
  basic: ["accuracy",'precision']
  robustness:
    adversarial: ["advacc","adverr","acac"]
    corruption: ["rmce"]
  interpretability: ["shap"]
  safety: ["auc","TPR@FPR=0.1%","attack_average_precision"]
  generalization: []
  fairness: []