# PyTorch分类器配置
model:
  instantiation:
    model_path: "model/net/ResNet.py"
    weight_path: "model/weight/resnet18_cifar10.pt"
    model_name: "ResNet18"
    parameters:
  estimator:
    framework: "pytorch"
    task: "classification"
    parameters:
      input_shape: [3, 32, 32]
      nb_classes: 10
      clip_values: [0,1]
      device: "cuda"
      device_type: "gpu"
evaluation:
  basic: ["accuracy",'precision']
  robustness:
    adversarial: ["advacc","adverr","acac"]
    corruption: ["rmce"]
  interpretability: ["shap"]
  safety: []
  generalization: []
  fairness: []