# PyTorch分类器配置
model:
  instantiation:
    model_path: "/app/userData/modelData/model/cifar10.py"
    weight_path: "app/userData/modelData/cifar_50.pth"
    model_name: "Tudui"
    parameters:
  estimator:
    framework: "pytorch"
    task: "classification"
    parameters:
      input_shape: [3, 32, 32]
      nb_classes: 10
      clip_values: [0,1]
      device: "cuda"
      device_type: "gpu"
attack:
  method: "fgsm"
  parameters:
    eps: 0.4