parameters:
  required:  # 必须提供的参数
  optional:   # 可选参数及默认值
    batch_size: 64
    targeted: False
    delta: 0.01
    epsilon: 0.01
    step_adapt: 0.667
    max_iter: 5000
    num_trial: 25
    sample_size: 20
    init_size: 100
    min_epsilon: 0.0
    verbose: True